#!/bin/sh

cp ~/.gitconfig ~/dot-files/
cp ~/.zshrc ~/dot-files/
cp ~/.vscode/argv.json ~/dot-files/

echo "Complete backup of dot files."

echo
echo "[ !!!IMPORTANT!!! ]"
echo "Please check NOT to write your e-mail address."
