#!/bin/sh

cp ~/.gitconfig ~/dot_files/.gitconfig
cp -r ~/.vim/ ~/dot_files/.vim
cp ~/.vimrc ~/dot_files/.vimrc
cp ~/.zshrc ~/dot_files/.zshrc

echo "Complete backup of dot files."

echo
echo "[ !!!IMPORTANT!!! ]"
echo "Please check NOT to write your e-mail address."
